
GET http://127.0.0.1:8000/api/users/show-all HTTP/1.1


###


PUT http://127.0.0.1:8000/api/users/update/1

Content-Type: application/json

{
    "fullName": "Mohab Mamdouh U",
    "username": "mohablog U",
}


###

GET http://127.0.0.1:8000/api/speaking-languages/show-all HTTP/1.1


###

PUT http://127.0.0.1:8000/api/speaking-languages/update/1

Content-Type: application/json

{
    "languageName": "ar",
    "level": "Level 0"
}


###

POST http://127.0.0.1:8000/api/speaking-languages/create HTTP/1.1

Content-Type: application/json

{
    "languageName": "ar",
    "level": "Level 0"
}
